name: difftastic
base: core20
adopt-info: difftastic
summary: Structured diff tool that compares files based on their syntax
description: |
  Difftastic is an experimental structured diff tool that compares files based
  on their syntax. It is very much unfinished. It works reasonably on very
  parenthesised data (lisps, JSON), it works sometimes on other languages with
  sufficient parentheses (Rust, JS), and falls back to a line-oriented diff
  otherwise.

grade: devel
confinement: strict

apps:
  difftastic:
    command: bin/difftastic
    plugs:
      - home

parts:
  difftastic:
    # See 'snapcraft plugins'
    plugin: rust
    source: https://github.com/wilfred/difftastic.git
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags)"
