name: difftastic
base: core20
version: 0.57.0
summary: Structured diff tool that compares files based on their syntax
description: |
  Difftastic is a structural diff tool that compares files based on their
  syntax.

  Difftastic supports over 30 programming languages.  If a file has an
  unrecognised extension, difftastic uses a textual diff with word
  highlighting.

  Difftastic output is intended for human consumption, and it does not
  generate patches that you can apply later. Use diff if you need a patch.

  To use the difftastic snap as an external diff tool with git, it should be
  invoked as:

      TMPDIR=~/tmp GIT_EXTERNAL_DIFF="difftastic" git diff

grade: stable
confinement: strict

apps:
  difftastic:
    command: bin/difft
    plugs:
      - home

parts:
  difftastic:
    plugin: rust
    source: https://github.com/wilfred/difftastic.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
